### PR TITLE
more efficient reordering

### PR DESCRIPTION
**Pull request by neonstalwart**
fixes Matt-Esch/virtual-dom#90

### CODE REVIEW

**Comment by neonstalwart** [comment]
this changes the reordering to work with the patch produced as a result of Matt-Esch/vtree#3

the idea is that the reordering inserts new nodes at indices that take into account mutations (move and remove) that are going to happen by the end of the patch but haven't happened yet.

**Comment by Matt-Esch** [comment]
@neonstalwart I am still in the process of thinking this through, sorry for the slow response on this. We do need to get this right. Just to give you an idea of my current thoughts, I actually started with something similar I think. Basically you realise that as you are shifting things around, the original indices get shifted. I also had vtree returning the inverse you compute so I think we are on the same page, I just need to verify in my head that we have caught all of the index shifts, as this was my problem last time.

**Comment by Matt-Esch** [comment]
I should also mention, this is still probably bad for moving the first item to the end. At least the side-effect of the unnecessary reorder was behaving consistently in every patch.

**Comment by neonstalwart** [comment]
I believe this should actually work extremely well for the case of moving the first element to the end. I haven't run the code to test it but walking through it by inspecting the code, there's just one move. 

my reasoning is that for the first element, the reverse index indicates that we should increase the insert offset. then `node` will be equal to `insertNode` for all iterations until we reach the last index where we bring the first node into the last position.

**Comment by neonstalwart** [comment]
in a similar way, removing the first node results in this algorithm not moving any of the nodes and then a subsequent patch operation removes that node.

**Pull request merged**
